# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1y284cxx59x1ql5108pzdgzfm9bf5lv2zcjn8lxqmfhxf8ij5q17";
    aarch64-linux = "094raadczrdi1bihcnnqa2i8g72s12cwnihcrgskby0qvs5dv5gi";
    x86_64-darwin = "117bq0p008g1mnprh6vdmqxfx6fc14dyxk4dhgn2k9g83ibdymfv";
    aarch64-darwin = "1rybp8pcfs8dq42zbvzab1vwq8wq383nxrnav103ghcb4xiljq24";
  };

  urlMap = {
    x86_64-linux = "https://github.com/fredrir/nsql/releases/download/v0.1.14/nsql-x86_64-unknown-linux-musl-v0.1.14.tar.gz";
    aarch64-linux = "https://github.com/fredrir/nsql/releases/download/v0.1.14/nsql-aarch64-unknown-linux-musl-v0.1.14.tar.gz";
    x86_64-darwin = "https://github.com/fredrir/nsql/releases/download/v0.1.14/nsql-x86_64-apple-darwin-v0.1.14.tar.gz";
    aarch64-darwin = "https://github.com/fredrir/nsql/releases/download/v0.1.14/nsql-aarch64-apple-darwin-v0.1.14.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "nsql";
  version = "0.1.14";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./nsql $out/bin/nsql
    runHook postInstall
  '';

  meta = {
    description = "Run SQL from your terminal, composed in your real neovim — without taking over the screen.";
    homepage = "https://github.com/fredrir/nsql";
    license = lib.licenses.bsd0;
    mainProgram = "nsql";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
