issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/packages(@1374225208)?:environment:publish$
claim_pattern:
  repository_id: ^1374225208$
  repository_owner_id: ^114402558$
  runner_environment: ^(self-hosted|github-hosted)$
  ref: ^refs/heads/main$
  event_name: ^(push|schedule|workflow_dispatch)$
  environment: ^publish$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/packages-publish\.yml@(25cbb5389a5d5df996709e2c5a1b4d1443861172|d9016b2889c88f1ec99bfe9d7262343a759e4b69)$
  job_workflow_sha: ^(25cbb5389a5d5df996709e2c5a1b4d1443861172|d9016b2889c88f1ec99bfe9d7262343a759e4b69)$
permissions:
  contents: write
