issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/packages(@1374225208)?:environment:publish$
claim_pattern:
  repository_id: ^1374225208$
  repository_owner_id: ^114402558$
  runner_environment: ^self-hosted$
  ref: ^refs/heads/main$
  event_name: ^(push|schedule|workflow_dispatch)$
  environment: ^publish$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/packages-publish\.yml@[0-9a-f]{40}$
permissions:
  contents: write
