issuer: https://token.actions.githubusercontent.com
subject_pattern: ^repo:fredrir(@114402558)?/packages(@1374225208)?:environment:publish$
claim_pattern:
  repository_id: ^1374225208$
  repository_owner_id: ^114402558$
  runner_environment: ^(self-hosted|github-hosted)$
  ref: ^refs/heads/main$
  event_name: ^(push|schedule|workflow_dispatch)$
  environment: ^publish$
  job_workflow_ref: ^fredrir/infra/\.github/workflows/packages-publish\.yml@(a57b0e15d5ca1c3180fba6a16cedbc7595e90610|cbbf64f0b9a383894e8f4c329d64b996260433c0)$
  job_workflow_sha: ^(a57b0e15d5ca1c3180fba6a16cedbc7595e90610|cbbf64f0b9a383894e8f4c329d64b996260433c0)$
permissions:
  contents: write
